apiVersion: v2
name: acm-switchover-rbac
description: RBAC resources for ACM Switchover automation tool
type: application
version: 1.4.9
appVersion: "1.4.9"
keywords:
  - acm
  - rbac
  - red-hat
  - openshift
  - kubernetes
home: https://github.com/tomazb/rh-acm-switchover
sources:
  - https://github.com/tomazb/rh-acm-switchover
maintainers:
  - name: Tomaz Borstnar
    email: tomaz@borstnar.com
icon: https://avatars.githubusercontent.com/u/tomazb
