{{- if or .Values.serviceAccounts.operator.create .Values.serviceAccounts.validator.create }}
{{- $ns := default .Release.Namespace .Values.namespace.name }}
{{- if .Values.serviceAccounts.operator.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "acm-switchover.operatorServiceAccountName" . }}
  namespace: {{ $ns }}
  labels:
    {{- include "acm-switchover.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
    app.kubernetes.io/role: operator
    {{- with .Values.serviceAccounts.operator.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccounts.operator.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
{{- if and .Values.serviceAccounts.operator.create .Values.serviceAccounts.validator.create }}
---
{{- end }}
{{- if .Values.serviceAccounts.validator.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "acm-switchover.validatorServiceAccountName" . }}
  namespace: {{ $ns }}
  labels:
    {{- include "acm-switchover.labels" . | nindent 4 }}
    app.kubernetes.io/component: validator
    app.kubernetes.io/role: validator
    {{- with .Values.serviceAccounts.validator.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccounts.validator.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
{{- end }}
