apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: acm-switchover-rbac-base
  annotations:
    config.kubernetes.io/local-config: "true"

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: acm-switchover
  app.kubernetes.io/part-of: acm-switchover
  app.kubernetes.io/managed-by: kustomize

resources:
  - ../../rbac/namespace.yaml
  - ../../rbac/serviceaccount.yaml
  - ../../rbac/clusterrole.yaml
  - ../../rbac/clusterrolebinding.yaml
  - ../../rbac/role.yaml
  - ../../rbac/rolebinding.yaml

# Namespace to apply resources to (except cluster-scoped resources)
namespace: acm-switchover
